name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/2024testback
            git config --global --add safe.directory /home/ubuntu/2024testback
            sudo git pull origin main
            sudo ./gradlew bootwar
            sudo fuser -k -n tcp 8080 
            nohup java -jar build/libs/*SNAPSHOT.war > /dev/null 2>&1 &